blank_issues_enabled: false
contact_links:
  - name: 👥 Discussions
    url:  https://github.com/tviles/KCDCCode2Cloud/discussions/new
    about: Please use discussions for issues that are not a bug, enhancement or feature request
